////////////////////////////////////////////////////////////////////////
// OpenTibia - an opensource roleplaying game
////////////////////////////////////////////////////////////////////////
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
////////////////////////////////////////////////////////////////////////
#include "otpch.h"

#include "localization.h"

#include <fstream>
#include <sstream>
#include <map>
#include <boost/regex.hpp>

typedef std::map<std::string, std::string> LocalizationMap;
//LocalizationMap en_us;
LocalizationMap pt_br;
LocalizationMap es_es;

std::map<LocalizationLang_t, LocalizationMap*> languages;                 
//std::map<std::string, uint32_t> PARSE_STRINGS;
//std::map<std::string, uint32_t> PARSE_STRINGS_REVERSE;

void LoadLocalizations()
{           
    /*PARSE_STRINGS["__L_NOTPOSSIBLE"] = __L_NOTPOSSIBLE;
	PARSE_STRINGS["__L_TILEISFULL"] = __L_TILEISFULL;
	PARSE_STRINGS["__L_YOUMAYNOTCASTAREAONBLACKSKULL"] = __L_YOUMAYNOTCASTAREAONBLACKSKULL;
	PARSE_STRINGS["__L_YOUARENOTTHEOWNER"] = __L_YOUARENOTTHEOWNER;
	PARSE_STRINGS["__L_CANONLYUSEONESHIELD"] = __L_CANONLYUSEONESHIELD;
	PARSE_STRINGS["__L_NAMEISTOOAMBIGUOUS"] = __L_NAMEISTOOAMBIGUOUS;
	PARSE_STRINGS["__L_YOUNEEDTOSPLITYOURSPEARS"] = __L_YOUNEEDTOSPLITYOURSPEARS;
	PARSE_STRINGS["__L_CANNOTCONJUREITEMHERE"] = __L_CANNOTCONJUREITEMHERE;
	PARSE_STRINGS["__L_YOUNEEDAMAGICITEMTOCASTSPELL"] = __L_YOUNEEDAMAGICITEMTOCASTSPELL;
	PARSE_STRINGS["__L_YOUCANNOTLOGOUTHERE"] = __L_YOUCANNOTLOGOUTHERE;
	PARSE_STRINGS["__L_ACTIONNOTPERMITTEDINANOPVPZONE"] = __L_ACTIONNOTPERMITTEDINANOPVPZONE;
	PARSE_STRINGS["__L_PLAYERISPZLOCKEDENTERPVPZONE"] = __L_PLAYERISPZLOCKEDENTERPVPZONE;
	PARSE_STRINGS["__L_PLAYERISPZLOCKEDLEAVEPVPZONE"] = __L_PLAYERISPZLOCKEDLEAVEPVPZONE;
	PARSE_STRINGS["__L_YOUNEEDAWEAPONTOUSETHISSPELL"] = __L_YOUNEEDAWEAPONTOUSETHISSPELL;
	PARSE_STRINGS["__L_YOURVOCATIONCANNOTUSETHISSPELL"] = __L_YOURVOCATIONCANNOTUSETHISSPELL;
	PARSE_STRINGS["__L_YOUNEEDTOLEARNTHISSPELL"] = __L_YOUNEEDTOLEARNTHISSPELL;
	PARSE_STRINGS["__L_YOUNEEDPREMIUMACCOUNT"] = __L_YOUNEEDPREMIUMACCOUNT;
	PARSE_STRINGS["__L_TURNSECUREMODETOATTACKUNMARKEDPLAYERS"] = __L_TURNSECUREMODETOATTACKUNMARKEDPLAYERS;
	PARSE_STRINGS["__L_YOUCANONLYUSEITONCREATURES"] = __L_YOUCANONLYUSEITONCREATURES;
	PARSE_STRINGS["__L_YOUMAYNOTATTACKAPERSONWHILEINPROTECTIONZONE"] = __L_YOUMAYNOTATTACKAPERSONWHILEINPROTECTIONZONE;
	PARSE_STRINGS["__L_YOUMAYNOTATTACKAPERSONINPROTECTIONZONE"] = __L_YOUMAYNOTATTACKAPERSONINPROTECTIONZONE;
	PARSE_STRINGS["__L_YOUMAYNOTATTACKTHISCREATURE"] = __L_YOUMAYNOTATTACKTHISCREATURE;
	PARSE_STRINGS["__L_YOUMAYNOTATTACKTHISPLAYER"] = __L_YOUMAYNOTATTACKTHISPLAYER;
	PARSE_STRINGS["__L_ACTIONNOTPERMITTEDINPROTECTIONZONE"] = __L_ACTIONNOTPERMITTEDINPROTECTIONZONE;
	PARSE_STRINGS["__L_CREATUREISNOTREACHABLE"] = __L_CREATUREISNOTREACHABLE;
	PARSE_STRINGS["__L_PLAYERISNOTREACHABLE"] = __L_PLAYERISNOTREACHABLE;
	PARSE_STRINGS["__L_CANONLYUSETHISRUNEONCREATURES"] = __L_CANONLYUSETHISRUNEONCREATURES;
	PARSE_STRINGS["__L_YOUAREEXHAUSTED"] = __L_YOUAREEXHAUSTED;
	PARSE_STRINGS["__L_NOTENOUGHSOUL"] = __L_NOTENOUGHSOUL;
	PARSE_STRINGS["__L_NOTENOUGHMANA"] = __L_NOTENOUGHMANA;
	PARSE_STRINGS["__L_NOTENOUGHMAGICLEVEL"] = __L_NOTENOUGHMAGICLEVEL;
	PARSE_STRINGS["__L_NOTENOUGHLEVEL"] = __L_NOTENOUGHLEVEL;
	PARSE_STRINGS["__L_DIRECTPLAYERSHOOT"] = __L_DIRECTPLAYERSHOOT;
	PARSE_STRINGS["__L_YOUMAYNOTLOGOUTDURINGAFIGHT"] = __L_YOUMAYNOTLOGOUTDURINGAFIGHT;
	PARSE_STRINGS["__L_THISPLAYERISALREADYTRADING"] = __L_THISPLAYERISALREADYTRADING;
	PARSE_STRINGS["__L_YOUAREALREADYTRADING"] = __L_YOUAREALREADYTRADING;
	PARSE_STRINGS["__L_NOTREQUIREDLEVELTOUSERUNE"] = __L_NOTREQUIREDLEVELTOUSERUNE;
	PARSE_STRINGS["__L_PLAYERWITHTHISNAMEISNOTONLINE"] = __L_PLAYERWITHTHISNAMEISNOTONLINE;
	PARSE_STRINGS["__L_CANNOTUSETHISOBJECT"] = __L_CANNOTUSETHISOBJECT;
	PARSE_STRINGS["__L_DEPOTISFULL"] = __L_DEPOTISFULL;
	PARSE_STRINGS["__L_CREATUREDOESNOTEXIST"] = __L_CREATUREDOESNOTEXIST;
	PARSE_STRINGS["__L_PLAYERISNOTINVITED"] = __L_PLAYERISNOTINVITED;
	PARSE_STRINGS["__L_PLAYERISPZLOCKED"] = __L_PLAYERISPZLOCKED;
	PARSE_STRINGS["__L_THISISIMPOSSIBLE"] = __L_THISISIMPOSSIBLE;
	PARSE_STRINGS["__L_THEREISNOWAY"] = __L_THEREISNOWAY;
	PARSE_STRINGS["__L_CANNOTTHROW"] = __L_CANNOTTHROW;
	PARSE_STRINGS["__L_CANNOTPICKUP"] = __L_CANNOTPICKUP;
	PARSE_STRINGS["__L_NOTENOUGHROOM"] = __L_NOTENOUGHROOM;
	PARSE_STRINGS["__L_NEEDEXCHANGE"] = __L_NEEDEXCHANGE;
	PARSE_STRINGS["__L_CONTAINERNOTENOUGHROOM"] = __L_CONTAINERNOTENOUGHROOM;
	PARSE_STRINGS["__L_NOTENOUGHCAPACITY"] = __L_NOTENOUGHCAPACITY;
	PARSE_STRINGS["__L_FIRSTGOUPSTAIRS"] = __L_FIRSTGOUPSTAIRS;
	PARSE_STRINGS["__L_FIRSTGODOWNSTAIRS"] = __L_FIRSTGODOWNSTAIRS;
	PARSE_STRINGS["__L_TOOFARAWAY"] = __L_TOOFARAWAY;
	PARSE_STRINGS["__L_CANONLYUSEONEWEAPON"] = __L_CANONLYUSEONEWEAPON;
	PARSE_STRINGS["__L_PUTTHISOBJECTINBOTHHANDS"] = __L_PUTTHISOBJECTINBOTHHANDS;
	PARSE_STRINGS["__L_PUTTHISOBJECTINYOURHAND"] = __L_PUTTHISOBJECTINYOURHAND;
	PARSE_STRINGS["__L_CANNOTBEDRESSED"] = __L_CANNOTBEDRESSED;
	PARSE_STRINGS["__L_BOTHHANDSNEEDTOBEFREE"] = __L_BOTHHANDSNEEDTOBEFREE;
	PARSE_STRINGS["__L_DROPTWOHANDEDITEM"] = __L_DROPTWOHANDEDITEM;
	PARSE_STRINGS["__L_NOTMOVEABLE"] = __L_NOTMOVEABLE;
	PARSE_STRINGS["__L_DESTINATIONOUTOFREACH"] = __L_DESTINATIONOUTOFREACH;
	PARSE_STRINGS["__L_YOURSELF"] = __L_YOURSELF;
	PARSE_STRINGS["__L_YOUARE"] = __L_YOUARE;
	PARSE_STRINGS["__L_YOUHAVENOVOCATION"] = __L_YOUHAVENOVOCATION;
	PARSE_STRINGS["__L_LEVEL"] = __L_LEVEL;
	PARSE_STRINGS["__L_HE"] = __L_HE;
	PARSE_STRINGS["__L_SHE"] = __L_SHE;
	PARSE_STRINGS["__L_IS"] = __L_IS;
	PARSE_STRINGS["__L_HASNOVOCATION"] = __L_HASNOVOCATION;
	PARSE_STRINGS["__L_FROM"] = __L_FROM;
	PARSE_STRINGS["__L_ANDYOUARE"] = __L_ANDYOUARE;
	PARSE_STRINGS["__L_ANDIS"] = __L_ANDIS;
	PARSE_STRINGS["__L_HUSBAND"] = __L_HUSBAND;
	PARSE_STRINGS["__L_WIFE"] = __L_WIFE;
	PARSE_STRINGS["__L_OF"] = __L_OF;
	PARSE_STRINGS["__L_AMEMBER"] = __L_AMEMBER;
	PARSE_STRINGS["__L_OFTHE"] = __L_OFTHE;
	PARSE_STRINGS["__L_ISWATCHINGTV"] = __L_ISWATCHINGTV;
	PARSE_STRINGS["__L_DEATHS"] = __L_DEATHS;
	PARSE_STRINGS["__L_YOUR"] = __L_YOUR;
	PARSE_STRINGS["__L_HASINCREASEDTO"] = __L_HASINCREASEDTO;
	PARSE_STRINGS["__L_HASLOGGEDIN"] = __L_HASLOGGEDIN;
	PARSE_STRINGS["__L_TARGETLOST"] = __L_TARGETLOST;
	PARSE_STRINGS["__L_HASLOGGEDOUT"] = __L_HASLOGGEDOUT;
	PARSE_STRINGS["__L_YOUAREMUTEDFORDSECONDS"] = __L_YOUAREMUTEDFORDSECONDS;
	PARSE_STRINGS["__L_YOULOSEDHITPOINTSDUETOANATTACKBYS"] = __L_YOULOSEDHITPOINTSDUETOANATTACKBYS;
	PARSE_STRINGS["__L_YOULOSEDHITPOINTS"] = __L_YOULOSEDHITPOINTS;
	PARSE_STRINGS["__L_YOULOSEDMANABLOCKINGANATTACKBYS"] = __L_YOULOSEDMANABLOCKINGANATTACKBYS;
	PARSE_STRINGS["__L_YOULOSEDMANA"] = __L_YOULOSEDMANA;
	PARSE_STRINGS["__L_YOUADVANCEDTOMAGICLEVELD"] = __L_YOUADVANCEDTOMAGICLEVELD;
	PARSE_STRINGS["__L_YOURECEIVEDDEXPERIENCEPOINTS"] = __L_YOURECEIVEDDEXPERIENCEPOINTS;
	PARSE_STRINGS["__L_YOUADVANCEDFROMLEVELDTOLEVELD"] = __L_YOUADVANCEDFROMLEVELDTOLEVELD;
	PARSE_STRINGS["__L_YOUWEREDOWNGRADEDFROMLEVELDTOLEVELD"] = __L_YOUWEREDOWNGRADEDFROMLEVELDTOLEVELD;
	PARSE_STRINGS["__L_YOURECOGNIZE"] = __L_YOURECOGNIZE;
	PARSE_STRINGS["__L_WASKILLEDBY"] = __L_WASKILLEDBY;
	PARSE_STRINGS["__L_SUMMONEDBY"] = __L_SUMMONEDBY;
	PARSE_STRINGS["__L_ANDBY"] = __L_ANDBY;
	PARSE_STRINGS["__L_YOUCANNOTADDYOURSELF"] = __L_YOUCANNOTADDYOURSELF;
	PARSE_STRINGS["__L_YOUCANNOTADDMOREBUDDIES"] = __L_YOUCANNOTADDMOREBUDDIES;
	PARSE_STRINGS["__L_THISPLAYERISALREADYINYOURLIST"] = __L_THISPLAYERISALREADYINYOURLIST;
	PARSE_STRINGS["__L_BURNING"] = __L_BURNING;
	PARSE_STRINGS["__L_POISONED"] = __L_POISONED;
	PARSE_STRINGS["__L_ELECTRIFIED"] = __L_ELECTRIFIED;
	PARSE_STRINGS["__L_FREEZING"] = __L_FREEZING;
	PARSE_STRINGS["__L_DAZZLED"] = __L_DAZZLED;
	PARSE_STRINGS["__L_CURSED"] = __L_CURSED;
	PARSE_STRINGS["__L_DROWNING"] = __L_DROWNING;
	PARSE_STRINGS["__L_DRUNK"] = __L_DRUNK;
	PARSE_STRINGS["__L_PROTECTEDBYAMAGICSHIELD"] = __L_PROTECTEDBYAMAGICSHIELD;
	PARSE_STRINGS["__L_PARALYZED"] = __L_PARALYZED;
	PARSE_STRINGS["__L_HASTED"] = __L_HASTED;
	PARSE_STRINGS["__L_STRENGTHENED"] = __L_STRENGTHENED;
	PARSE_STRINGS["__L_YOUDEALDDAMAGETOS"] = __L_YOUDEALDDAMAGETOS;
	PARSE_STRINGS["__L_YOURSDEALSDDAMAGETOS"] = __L_YOURSDEALSDDAMAGETOS;
	PARSE_STRINGS["__L_YOUHAVEBEENBANISHED"] = __L_YOUHAVEBEENBANISHED;
	PARSE_STRINGS["__L_YOURNAMEYOUWANTISTOOSHORTPLEASESELECTALONGERNAME"] = __L_YOURNAMEYOUWANTISTOOSHORTPLEASESELECTALONGERNAME;
	PARSE_STRINGS["__L_THENAMEYOUWANTISTOOLONGPLEASESELECTASHORTERNAME"] = __L_THENAMEYOUWANTISTOOLONGPLEASESELECTASHORTERNAME;
	PARSE_STRINGS["__L_THATNAMESEEMSTOCONTAININVALIDSYMBOLSPLEASECHOOSEANOTHERNAME"] = __L_THATNAMESEEMSTOCONTAININVALIDSYMBOLSPLEASECHOOSEANOTHERNAME;
	PARSE_STRINGS["__L_APLAYERWITHTHATNAMEALREADYEXISTSPLEASECHOOSEANOTHERNAME"] = __L_APLAYERWITHTHATNAMEALREADYEXISTSPLEASECHOOSEANOTHERNAME;
	PARSE_STRINGS["__L_AREYOUSURE"] = __L_AREYOUSURE;
	PARSE_STRINGS["__L_YOURCHARACTERISNOTASTAFFMEMBERPLEASETELLMEANOTHERNAME"] = __L_YOURCHARACTERISNOTASTAFFMEMBERPLEASETELLMEANOTHERNAME;
	PARSE_STRINGS["__L_WHATELSEWOULDYOULIKETONAMEYOURCHARACTER"] = __L_WHATELSEWOULDYOULIKETONAMEYOURCHARACTER;
	PARSE_STRINGS["__L_YOURCHARACTERHASBEENSUCCESSFULLYRENAMEDYOUSHOULDNOWBEABLETOLOGINATITWI"] = __L_YOURCHARACTERHASBEENSUCCESSFULLYRENAMEDYOUSHOULDNOWBEABLETOLOGINATITWI;
	PARSE_STRINGS["__L_FAILEDTOCHANGEYOURNAMEPLEASETRYAGAIN"] = __L_FAILEDTOCHANGEYOURNAMEPLEASETRYAGAIN;
	PARSE_STRINGS["__L_SORRYBUTICANTUNDERSTANDYOUPLEASETRYTOREPEATTHAT"] = __L_SORRYBUTICANTUNDERSTANDYOUPLEASETRYTOREPEATTHAT;
	PARSE_STRINGS["__L_DOYOUWANTTOCHANGEYOURPASSWORDREQUESTARECOVERYKEYADDACHARACTERORDELETEA"] = __L_DOYOUWANTTOCHANGEYOURPASSWORDREQUESTARECOVERYKEYADDACHARACTERORDELETEA;
	PARSE_STRINGS["__L_WHICHCHARACTERWOULDYOULIKETODELETE"] = __L_WHICHCHARACTERWOULDYOULIKETODELETE;
	PARSE_STRINGS["__L_THATNAMECONTAINSINVALIDCHARACTERSTRYTOSAYYOURNAMEAGAINYOUMIGHTHAVETYPE"] = __L_THATNAMECONTAINSINVALIDCHARACTERSTRYTOSAYYOURNAMEAGAINYOUMIGHTHAVETYPE;
	PARSE_STRINGS["__L_DOYOUREALLYWANTTODELETETHECHARACTERNAMED"] = __L_DOYOUREALLYWANTTODELETETHECHARACTERNAMED;
	PARSE_STRINGS["__L_ANERROROCCUREDWHILEDELETINGYOURCHARACTEREITHERTHECHARACTERDOESNOTBELON"] = __L_ANERROROCCUREDWHILEDELETINGYOURCHARACTEREITHERTHECHARACTERDOESNOTBELON;
	PARSE_STRINGS["__L_YOURCHARACTERHASBEENDELETED"] = __L_YOURCHARACTERHASBEENDELETED;
	PARSE_STRINGS["__L_YOURCHARACTEROWNSAHOUSETOMAKESUREYOUREALLYWANTTOLOSEYOURHOUSEBYDELETIN"] = __L_YOURCHARACTEROWNSAHOUSETOMAKESUREYOUREALLYWANTTOLOSEYOURHOUSEBYDELETIN;
	PARSE_STRINGS["__L_YOURCHARACTERISTHELEADEROFAGUILDYOUNEEDTODISBANDORPASSTHELEADERSHIPSOM"] = __L_YOURCHARACTERISTHELEADEROFAGUILDYOUNEEDTODISBANDORPASSTHELEADERSHIPSOM;
	PARSE_STRINGS["__L_ACHARACTERWITHTHATNAMEISCURRENTLYONLINETODELETEACHARACTERITHASTOBEOFFL"] = __L_ACHARACTERWITHTHATNAMEISCURRENTLYONLINETODELETEACHARACTERITHASTOBEOFFL;
	PARSE_STRINGS["__L_TELLMEWHATCHARACTERYOUWANTTODELETE"] = __L_TELLMEWHATCHARACTERYOUWANTTODELETE;
	PARSE_STRINGS["__L_TELLMEYOURNEWPASSWORDPLEASE"] = __L_TELLMEYOURNEWPASSWORDPLEASE;
	PARSE_STRINGS["__L_THATPASSWORDISTOOSHORTATLEAST6DIGITSAREREQUIREDPLEASESELECTALONGERPASS"] = __L_THATPASSWORDISTOOSHORTATLEAST6DIGITSAREREQUIREDPLEASESELECTALONGERPASS;
	PARSE_STRINGS["__L_YOURPASSWORDCONTAINSINVALIDCHARACTERSPLEASETELLMEANOTHERONE"] = __L_YOURPASSWORDCONTAINSINVALIDCHARACTERSPLEASETELLMEANOTHERONE;
	PARSE_STRINGS["__L_SHOULD"] = __L_SHOULD;
	PARSE_STRINGS["__L_BEYOURNEWPASSWORD"] = __L_BEYOURNEWPASSWORD;
	PARSE_STRINGS["__L_YOURPASSWORDHASBEENCHANGED"] = __L_YOURPASSWORDHASBEENCHANGED;
	PARSE_STRINGS["__L_THENNOT"] = __L_THENNOT;
	PARSE_STRINGS["__L_WHATWOULDYOULIKEASYOURCHARACTERNAME"] = __L_WHATWOULDYOULIKEASYOURCHARACTERNAME;
	PARSE_STRINGS["__L_YOURACCOUNTREACHTHELIMITOF15PLAYERSYOUCANDELETEACHARACTERIFYOUWANTTOCR"] = __L_YOURACCOUNTREACHTHELIMITOF15PLAYERSYOUCANDELETEACHARACTERIFYOUWANTTOCR;
	PARSE_STRINGS["__L_SHOULDYOURCHARACTERBEAMALEORAFEMALE"] = __L_SHOULDYOURCHARACTERBEAMALEORAFEMALE;
	PARSE_STRINGS["__L_AFEMALEAREYOUSURE"] = __L_AFEMALEAREYOUSURE;
	PARSE_STRINGS["__L_AMALEAREYOUSURE"] = __L_AMALEAREYOUSURE;
	PARSE_STRINGS["__L_TELLMEWOULDYOULIKETOBEAMALEORAFEMALE"] = __L_TELLMEWOULDYOULIKETOBEAMALEORAFEMALE;
	PARSE_STRINGS["__L_WHATDOYOUWANTTOBE"] = __L_WHATDOYOUWANTTOBE;
	PARSE_STRINGS["__L_OR"] = __L_OR;
	PARSE_STRINGS["__L_YOURCHARACTERHASBEENCREATED"] = __L_YOURCHARACTERHASBEENCREATED;
	PARSE_STRINGS["__L_YOURCHARACTERCOULDNTBECREATEDPLEASETRYAGAIN"] = __L_YOURCHARACTERCOULDNTBECREATEDPLEASETRYAGAIN;
	PARSE_STRINGS["__L_SOYOUWOULDLIKETOBE"] = __L_SOYOUWOULDLIKETOBE;
	PARSE_STRINGS["__L_IDONTUNDERSTANDWHATVOCATIONYOUWOULDLIKETOBECOULDYOUPLEASEREPEATIT"] = __L_IDONTUNDERSTANDWHATVOCATIONYOUWOULDLIKETOBECOULDYOUPLEASEREPEATIT;
	PARSE_STRINGS["__L_NOTHENWHATWOULDYOULIKETOBE"] = __L_NOTHENWHATWOULDYOULIKETOBE;
	PARSE_STRINGS["__L_WOULDYOULIKEARECOVERYKEY"] = __L_WOULDYOULIKEARECOVERYKEY;
	PARSE_STRINGS["__L_SORRYYOUALREADYHAVEARECOVERYKEYFORSECURITYREASONSIMAYNOTGIVEYOUANEWONE"] = __L_SORRYYOUALREADYHAVEARECOVERYKEYFORSECURITYREASONSIMAYNOTGIVEYOUANEWONE;
	PARSE_STRINGS["__L_YOURRECOVERYKEYIS"] = __L_YOURRECOVERYKEYIS;
	PARSE_STRINGS["__L_PLEASEREADTHELATESTMESSAGETHATIHAVESPECIFIEDIDONTUNDERSTANDTHECURRENTR"] = __L_PLEASEREADTHELATESTMESSAGETHATIHAVESPECIFIEDIDONTUNDERSTANDTHECURRENTR;
	PARSE_STRINGS["__L_WHATWOULDYOULIKEYOURPASSWORDTOBE"] = __L_WHATWOULDYOULIKEYOURPASSWORDTOBE;
	PARSE_STRINGS["__L_ISITYESORNO"] = __L_ISITYESORNO;
	PARSE_STRINGS["__L_YOURACCOUNTHASBEENCREATEDYOUMAYMANAGEITNOWBUTREMEMBERYOURACCOUNTNAME"] = __L_YOURACCOUNTHASBEENCREATEDYOUMAYMANAGEITNOWBUTREMEMBERYOURACCOUNTNAME;
	PARSE_STRINGS["__L_ANDPASSWORD"] = __L_ANDPASSWORD;
	PARSE_STRINGS["__L_IFTHEACCOUNTNAMEISTOOHARDTOREMEMBERPLEASENOTEITSOMEWHERE"] = __L_IFTHEACCOUNTNAMEISTOOHARDTOREMEMBERPLEASENOTEITSOMEWHERE;
	PARSE_STRINGS["__L_YOURACCOUNTCOULDNOTBECREATEDPLEASETRYAGAIN"] = __L_YOURACCOUNTCOULDNOTBECREATEDPLEASETRYAGAIN;
	PARSE_STRINGS["__L_WHATWOULDYOULIKEYOURACCOUNTNAMETOBE"] = __L_WHATWOULDYOULIKEYOURACCOUNTNAMETOBE;
	PARSE_STRINGS["__L_WHATWOULDYOULIKEYOURPASSWORDTOBETHEN"] = __L_WHATWOULDYOULIKEYOURPASSWORDTOBETHEN;
	PARSE_STRINGS["__L_THATACCOUNTNAMEISTOOSHORTATLEAST3DIGITSAREREQUIREDPLEASESELECTALONGERA"] = __L_THATACCOUNTNAMEISTOOSHORTATLEAST3DIGITSAREREQUIREDPLEASESELECTALONGERA;
	PARSE_STRINGS["__L_THATACCOUNTNAMEISTOOLONGNOTMORETHAN25DIGITSAREREQUIREDPLEASESELECTASHO"] = __L_THATACCOUNTNAMEISTOOLONGNOTMORETHAN25DIGITSAREREQUIREDPLEASESELECTASHO;
	PARSE_STRINGS["__L_YOURACCOUNTNAMECONTAINSINVALIDCHARACTERSPLEASECHOOSEANOTHERONE"] = __L_YOURACCOUNTNAMECONTAINSINVALIDCHARACTERSPLEASECHOOSEANOTHERONE;
	PARSE_STRINGS["__L_YOURACCOUNTNAMECANNOTBESAMEASPASSWORDPLEASECHOOSEANOTHERONE"] = __L_YOURACCOUNTNAMECANNOTBESAMEASPASSWORDPLEASECHOOSEANOTHERONE;
	PARSE_STRINGS["__L_ANACCOUNTWITHTHATNAMEALREADYEXISTSPLEASETRYANOTHERACCOUNTNAME"] = __L_ANACCOUNTWITHTHATNAMEALREADYEXISTSPLEASETRYANOTHERACCOUNTNAME;
	PARSE_STRINGS["__L_WHATELSEWOULDYOULIKEASYOURACCOUNTNAME"] = __L_WHATELSEWOULDYOULIKEASYOURACCOUNTNAME;
	PARSE_STRINGS["__L_WHATWASYOURACCOUNTNAME"] = __L_WHATWASYOURACCOUNTNAME;
	PARSE_STRINGS["__L_WHATWASYOURRECOVERYKEY"] = __L_WHATWASYOURRECOVERYKEY;
	PARSE_STRINGS["__L_SORRYBUTACCOUNTWITHSUCHNAMEDOESNTEXISTS"] = __L_SORRYBUTACCOUNTWITHSUCHNAMEDOESNTEXISTS;
	PARSE_STRINGS["__L_CORRECTYOURNEWPASSWORDIS"] = __L_CORRECTYOURNEWPASSWORDIS;
	PARSE_STRINGS["__L_SORRYBUTTHISKEYDOESNTMATCHTOACCOUNTYOUGAVEME"] = __L_SORRYBUTTHISKEYDOESNTMATCHTOACCOUNTYOUGAVEME;
	PARSE_STRINGS["__L_HINTTYPEACCOUNTTOMANAGEYOURACCOUNTANDIFYOUWANTTOSTARTOVERTHENTYPECANCE"] = __L_HINTTYPEACCOUNTTOMANAGEYOURACCOUNTANDIFYOUWANTTOSTARTOVERTHENTYPECANCE;
	PARSE_STRINGS["__L_CRITICAL"] = __L_CRITICAL;
	PARSE_STRINGS["__L_LOOTCOLLECTED"] = __L_LOOTCOLLECTED;
	PARSE_STRINGS["__L_LOOTNOTCOLLECTEDCHECKYOURBACKPACK"] = __L_LOOTNOTCOLLECTEDCHECKYOURBACKPACK;
	PARSE_STRINGS["__L_ISSLEEPINGTHERE"] = __L_ISSLEEPINGTHERE;
	PARSE_STRINGS["__L_NOBODYISSLEEPINGTHERE"] = __L_NOBODYISSLEEPINGTHERE;
	PARSE_STRINGS["__L_INVITESYOUTO"] = __L_INVITESYOUTO;
	PARSE_STRINGS["__L_HIS"] = __L_HIS;
	PARSE_STRINGS["__L_HER"] = __L_HER;
	PARSE_STRINGS["__L_PRIVATECHATCHANNEL"] = __L_PRIVATECHATCHANNEL;
	PARSE_STRINGS["__L_HASBEENINVITED"] = __L_HASBEENINVITED;
	PARSE_STRINGS["__L_HASBEENEXCLUDED"] = __L_HASBEENEXCLUDED;
	PARSE_STRINGS["__L_NEWVIEWER"] = __L_NEWVIEWER;
	PARSE_STRINGS["__L_HASLEFTFROMYOURTVCHANNEL"] = __L_HASLEFTFROMYOURTVCHANNEL;
	PARSE_STRINGS["__L_YOUHAVEBEENBANNEDFROM"] = __L_YOUHAVEBEENBANNEDFROM;
	PARSE_STRINGS["__L_TVCHANNEL"] = __L_TVCHANNEL;
	PARSE_STRINGS["__L_HASBEENBANNEDFROMYOURTVCHANNEL"] = __L_HASBEENBANNEDFROMYOURTVCHANNEL;
	PARSE_STRINGS["__L_YOUHAVEBEENUNBANNEDFROM"] = __L_YOUHAVEBEENUNBANNEDFROM;
	PARSE_STRINGS["__L_HASBEENUNBANNEDFROMYOURTVCHANNEL"] = __L_HASBEENUNBANNEDFROMYOURTVCHANNEL;
	PARSE_STRINGS["__L_CHANNEL"] = __L_CHANNEL;
	PARSE_STRINGS["__L_YOUMAYNOTSPEAKINTOTHISCHANNEL"] = __L_YOUMAYNOTSPEAKINTOTHISCHANNEL;
	PARSE_STRINGS["__L_YOUMAYNOTSPEAKINTOTHISCHANNELASLONGASYOUAREONLEVELD"] = __L_YOUMAYNOTSPEAKINTOTHISCHANNELASLONGASYOUAREONLEVELD;
	PARSE_STRINGS["__L_YOUARENOTINAGUILD"] = __L_YOUARENOTINAGUILD;
	PARSE_STRINGS["__L_ITSEEMSLIKEYOURGUILDDOESNOTEXISTANYMORE"] = __L_ITSEEMSLIKEYOURGUILDDOESNOTEXISTANYMORE;
	PARSE_STRINGS["__L_THEGUILDHASBEENDISBANDED"] = __L_THEGUILDHASBEENDISBANDED;
	PARSE_STRINGS["__L_YOUARENOTTHELEADEROFYOURGUILD"] = __L_YOUARENOTTHELEADEROFYOURGUILD;
	PARSE_STRINGS["__L_SHASINVITEDYOUTOJOINTHEGUILDSYOUMAYJOINTHISGUILDBYWRITINGJOINGUILDS"] = __L_SHASINVITEDYOUTOJOINTHEGUILDSYOUMAYJOINTHISGUILDBYWRITINGJOINGUILDS;
	PARSE_STRINGS["__L_SHASINVITEDSTOTHEGUILD"] = __L_SHASINVITEDSTOTHEGUILD;
	PARSE_STRINGS["__L_APLAYERWITHTHATNAMEHASALREADYBEENINVITEDTOYOURGUILD"] = __L_APLAYERWITHTHATNAMEHASALREADYBEENINVITEDTOYOURGUILD;
	PARSE_STRINGS["__L_APLAYERWITHTHATNAMEISALREADYINAGUILD"] = __L_APLAYERWITHTHATNAMEISALREADYINAGUILD;
	PARSE_STRINGS["__L_YOURGUILDDOESNOTEXISTANYMORE"] = __L_YOURGUILDDOESNOTEXISTANYMORE;
	PARSE_STRINGS["__L_APLAYERWITHTHATNAMEDOESNOTEXIST"] = __L_APLAYERWITHTHATNAMEDOESNOTEXIST;
	PARSE_STRINGS["__L_INVALIDGUILDCOMMANDPARAMETERS"] = __L_INVALIDGUILDCOMMANDPARAMETERS;
	PARSE_STRINGS["__L_YOUDONTHAVERIGHTSTOINVITEPLAYERSTOYOURGUILD"] = __L_YOUDONTHAVERIGHTSTOINVITEPLAYERSTOYOURGUILD;
	PARSE_STRINGS["__L_SHASLEFTTHEGUILD"] = __L_SHASLEFTTHEGUILD;
	PARSE_STRINGS["__L_YOUCANNOTLEAVEYOURGUILDBECAUSEYOUARETHELEADEROFITYOUHAVETOPASSTHELEADE"] = __L_YOUCANNOTLEAVEYOURGUILDBECAUSEYOUARETHELEADEROFITYOUHAVETOPASSTHELEADE;
	PARSE_STRINGS["__L_SHASREVOKEDYOURINVITETOSGUILD"] = __L_SHASREVOKEDYOURINVITETOSGUILD;
	PARSE_STRINGS["__L_SHASREVOKEDTHEGUILDINVITEOFS"] = __L_SHASREVOKEDTHEGUILDINVITEOFS;
	PARSE_STRINGS["__L_APLAYERWITHTHATNAMEISNOTINVITEDTOYOURGUILD"] = __L_APLAYERWITHTHATNAMEISNOTINVITEDTOYOURGUILD;
	PARSE_STRINGS["__L_YOUDONTHAVERIGHTSTOREVOKEANINVITEOFSOMEONEINYOURGUILD"] = __L_YOUDONTHAVERIGHTSTOREVOKEANINVITEOFSOMEONEINYOURGUILD;
	PARSE_STRINGS["__L_SHASPROMOTEDSTOS"] = __L_SHASPROMOTEDSTOS;
	PARSE_STRINGS["__L_APLAYERWITHTHATNAMEDOESNOTHAVEAPREMIUMACCOUNT"] = __L_APLAYERWITHTHATNAMEDOESNOTHAVEAPREMIUMACCOUNT;
	PARSE_STRINGS["__L_YOUCANONLYPROMOTEMEMBERSTOVICELEADERS"] = __L_YOUCANONLYPROMOTEMEMBERSTOVICELEADERS;
	PARSE_STRINGS["__L_SHASDEMOTEDSTOS"] = __L_SHASDEMOTEDSTOS;
	PARSE_STRINGS["__L_YOUCANONLYDEMOTEVICELEADERSTOMEMBERS"] = __L_YOUCANONLYDEMOTEVICELEADERSTOMEMBERS;
	PARSE_STRINGS["__L_SHASPASSEDTHEGUILDLEADERSHIPTOS"] = __L_SHASPASSEDTHEGUILDLEADERSHIPTOS;
	PARSE_STRINGS["__L_THENEWGUILDLEADERHASTOBEATLEASTLEVELD"] = __L_THENEWGUILDLEADERHASTOBEATLEASTLEVELD;
	PARSE_STRINGS["__L_APLAYERWITHTHATNAMEISNOTAVICELEADER"] = __L_APLAYERWITHTHATNAMEISNOTAVICELEADER;
	PARSE_STRINGS["__L_SHASBEENKICKEDFROMTHEGUILDBYS"] = __L_SHASBEENKICKEDFROMTHEGUILDBYS;
	PARSE_STRINGS["__L_YOUMAYONLYKICKPLAYERSWITHAGUILDRANKBELOWYOUR"] = __L_YOUMAYONLYKICKPLAYERSWITHAGUILDRANKBELOWYOUR;
	PARSE_STRINGS["__L_YOUARENOTINTHESAMEGUILDASAPLAYERWITHTHATNAME"] = __L_YOUARENOTINTHESAMEGUILDASAPLAYERWITHTHATNAME;
	PARSE_STRINGS["__L_COULDNOTFINDTHEGUILDOFAPLAYERWITHTHATNAME"] = __L_COULDNOTFINDTHEGUILDOFAPLAYERWITHTHATNAME;
	PARSE_STRINGS["__L_APLAYERWITHTHATNAMEISNOTINAGUILD"] = __L_APLAYERWITHTHATNAMEISNOTINAGUILD;
	PARSE_STRINGS["__L_SHASSETTHEGUILDNICKOFSTOS"] = __L_SHASSETTHEGUILDNICKOFSTOS;
	PARSE_STRINGS["__L_SHASSETSGUILDNICKTOS"] = __L_SHASSETSGUILDNICKTOS;
	PARSE_STRINGS["__L_YOUMAYONLYCHANGETHEGUILDNICKOFPLAYERSTHATHAVEALOWERRANKTHANYOU"] = __L_YOUMAYONLYCHANGETHEGUILDNICKOFPLAYERSTHATHAVEALOWERRANKTHANYOU;
	PARSE_STRINGS["__L_APLAYERWITHTHATNAMEISNOTINYOURGUILD"] = __L_APLAYERWITHTHATNAMEISNOTINYOURGUILD;
	PARSE_STRINGS["__L_APLAYERWITHTHATNAMESGUILDCOULDNOTBEFOUND"] = __L_APLAYERWITHTHATNAMESGUILDCOULDNOTBEFOUND;
	PARSE_STRINGS["__L_THATGUILDNICKISNOTVALID"] = __L_THATGUILDNICKISNOTVALID;
	PARSE_STRINGS["__L_THATGUILDNICKISTOOLONGPLEASESELECTASHORTERONE"] = __L_THATGUILDNICKISTOOLONGPLEASESELECTASHORTERONE;
	PARSE_STRINGS["__L_THATGUILDNICKISTOOSHORTPLEASESELECTALONGERONE"] = __L_THATGUILDNICKISTOOSHORTPLEASESELECTALONGERONE;
	PARSE_STRINGS["__L_APLAYERWITHTHATNAMEISNOTINANYGUILD"] = __L_APLAYERWITHTHATNAMEISNOTINANYGUILD;
	PARSE_STRINGS["__L_SHASRENAMEDTHEGUILDRANKSTOS"] = __L_SHASRENAMEDTHEGUILDRANKSTOS;
	PARSE_STRINGS["__L_THEREISALREADYARANKINYOURGUILDWITHTHATNAME"] = __L_THEREISALREADYARANKINYOURGUILDWITHTHATNAME;
	PARSE_STRINGS["__L_THEREISNOSUCHRANKNAMEINYOURGUILD"] = __L_THEREISNOSUCHRANKNAMEINYOURGUILD;
	PARSE_STRINGS["__L_THENEWGUILDRANKCONTAINSINVALIDCHARACTERS"] = __L_THENEWGUILDRANKCONTAINSINVALIDCHARACTERS;
	PARSE_STRINGS["__L_THENEWRANKNAMEISTOOLONG"] = __L_THENEWRANKNAMEISTOOLONG;
	PARSE_STRINGS["__L_THENEWRANKNAMEISTOOSHORT"] = __L_THENEWRANKNAMEISTOOSHORT;
	PARSE_STRINGS["__L_SHASSETTHEMESSAGEOFTHEDAYTOS"] = __L_SHASSETTHEMESSAGEOFTHEDAYTOS;
	PARSE_STRINGS["__L_THATMOTDISTOOLONG"] = __L_THATMOTDISTOOLONG;
	PARSE_STRINGS["__L_THATMOTDISTOOSHORT"] = __L_THATMOTDISTOOSHORT;
	PARSE_STRINGS["__L_ONLYTHELEADEROFYOURGUILDCANSETTHEGUILDMOTD"] = __L_ONLYTHELEADEROFYOURGUILDCANSETTHEGUILDMOTD;
	PARSE_STRINGS["__L_SHASCLEANEDTHEMESSAGEOFTHEDAY"] = __L_SHASCLEANEDTHEMESSAGEOFTHEDAY;
	PARSE_STRINGS["__L_ONLYTHELEADEROFYOURGUILDCANCLEANTHEGUILDMOTD"] = __L_ONLYTHELEADEROFYOURGUILDCANCLEANTHEGUILDMOTD;
	PARSE_STRINGS["__L_THATMESSAGEISTOOLONG"] = __L_THATMESSAGEISTOOLONG;
	PARSE_STRINGS["__L_THATMESSAGEISTOOSHORT"] = __L_THATMESSAGEISTOOSHORT;
	PARSE_STRINGS["__L_ONLYTHELEADEROFYOURGUILDCANBROADCAST"] = __L_ONLYTHELEADEROFYOURGUILDCANBROADCAST;
	PARSE_STRINGS["__L_GUILDCOMMANDSWITHPARAMETERSDISBANDLEAVEKICKNAMEREVOKENAMEDEMOTENAMEPRO"] = __L_GUILDCOMMANDSWITHPARAMETERSDISBANDLEAVEKICKNAMEREVOKENAMEDEMOTENAMEPRO;*/

    std::ifstream input("pt_br.loc");
    
    for (std::string line; getline(input, line);) {
        std::istringstream ss(line);
        std::string token;
        
        std::string id = "";
        std::string value = "";
        
        while (std::getline(ss, token, '@')) {
            if (id == "") {
                id = token;
            }
            else {
                value = token;
            }
        }
        //pt_br[PARSE_STRINGS[id]] = value;
                pt_br[(boost::regex_replace(id, boost::regex("\\\\n"), "\n"))] = (boost::regex_replace(value, boost::regex("\\\\n"), "\n"));
    }
    
    //languages[LANG_EN_US] = &en_us;
    languages[LANG_PT_BR] = &pt_br;
    languages[LANG_ES_ES] = &es_es;
}

Localization::Localization()
{
    LoadLocalizations();
}

Localization::~Localization()
{
}

/*std::string Localization::t(LocalizationLang_t lang, LocalizationString_t local)
{
    return (*languages[lang])[local];
}*/

std::string Localization::t(LocalizationLang_t lang, std::string localString)
{
    if (lang != LANG_EN_US) {
        try {
            if ((*languages[lang]).count(localString)) {
                //return (*languages[lang])[PARSE_STRINGS_REVERSE[localString]];
                return (*languages[lang])[localString];
            }
        }
        catch(...) {}
    }
    return localString;
}
